In [2]:
import json
import numpy as np
import pandas as pd
import os

In [3]:
path = 'json/'
filename = [] #json資料夾下所有檔案名稱(YYYY-MM-DD.json)
DF_list = []  #YYYY-MM-DD

for i in os.listdir(path):
    filename.append(i)
    DF_list.append(i[:-5])

In [4]:
day = input()
day_index = DF_list.index(day)

2018-10-01


In [5]:
#------------Stored testing data---------------
files_recent = {}
fr_list = []
count = 3

for i in range(day_index-count,day_index):
    fr_list.append(filename[i][:-5])
    with open(path+filename[i]) as f:
        symbol_f = json.load(f)
    files_recent[filename[i][:-5]] = symbol_f
    f.close

print(fr_list)

['2018-09-26', '2018-09-27', '2018-09-28']


In [6]:
#Stock_sym = [sym for sym in files_recent[fr_list[-1]].keys()]
#Stock_sym.remove('id')
Stock_sym = ['0050','0051','0052']
Stock_feature = []
Close = []
Open = []
Volume = []

for symbol in Stock_sym:
    tmp = []
    for i in range(0,count):
        if symbol not in files_recent[fr_list[-1-i]].keys():
            break
        for attr in ['open','close','volume']: #['adj_close','close','high','low','open','volume']:
            if files_recent[fr_list[-1-i]][symbol][attr] == None or files_recent[fr_list[-1-i]][symbol][attr] == 'NULL':
                break
            tmp.append(float(files_recent[fr_list[-1-i]][symbol][attr]))
    if len(tmp) != 9:
        continue
    Stock_feature.append(tmp)

    
for p in range(len(Stock_feature)):
    O = []
    C = []
    V = []
    for q in range(len(Stock_feature[0])):
        if (q+1)%3 == 1:
            O.append(Stock_feature[p][q])
        if (q+1)%3 == 2:
            C.append(Stock_feature[p][q])
        if (q+1)%3 == 0:
            V.append(Stock_feature[p][q])
    Open.append(O)
    Close.append(C)
    Volume.append(V)

In [7]:
Feature = []
for i in range(3):
    ftmp = []
    ftmp.append(round(sum(map(float,Open[i]))/3. , 2))
    ftmp.append(round(sum(map(float,Close[i]))/3. , 2))
    ftmp.append(max(Volume[i]))
    
    Feature.append(ftmp)

In [8]:
print(Feature)

[[86.95, 87.05, 27800036.0], [32.91, 32.79, 43000.0], [55.8, 56.0, 109397.0]]


In [10]:
Feature = np.array(Feature)

In [11]:
print(Feature)

[[8.6950000e+01 8.7050000e+01 2.7800036e+07]
 [3.2910000e+01 3.2790000e+01 4.3000000e+04]
 [5.5800000e+01 5.6000000e+01 1.0939700e+05]]
